### ISSUE TITLE
Add hook when attachment is attached

### ISSUE THREAD

**Issue by Heyter** [HaodongMo/ArcCW#76]
Add the hook when the attachment has been successfully added to the weapon.

**Comment by Heyter** [comment]
Also need a hook like in TFA.
```lua
TFA_FinalInitAttachments(wepom) --final attachment init hook
```

**Comment by TheOnly8Z** [comment]
Can't implement with any guarantee of the hook running since there are many situations where attachments are modified without calling `SWEP.Attach`, directly changing the `SWEP.Attachments` table instead.

If you need some sort of initialize context, add a think hook and a variable check to run it once.
